### ISSUE TITLE
Snippet for react-tabs not working: Reference Error, App is not defined

### ISSUE THREAD

**Issue by Kothari-Anshul** [jyash97/snippet-to-codesandbox#3]
Steps to reproduce:

1. Visit https://www.npmjs.com/package/react-tabs
2. Select snippet under Basic Example head
3. Right-click -> open in code-sandbox -> React
![codesandbox_error](https://user-images.githubusercontent.com/22186830/94359819-d6ab3080-00c6-11eb-9399-34789384880b.PNG)

**Comment by jyash97** [comment]
Thanks for pointing out the issue. 

It seems to be working with the latest code and all the tests seem to pass. Could not replicate the issue but have pushed a new version that would be released after the changes are approved by the Chrome team.

Thanks 💯
